### ISSUE TITLE
InfluxDB Configuration URL

### ISSUE THREAD

**Issue by mjlyon** [pstadler/metrics.sh#3]
The influxdb configuration URLs aren't given as an example syntax, and trying from:

https://docs.influxdata.com/influxdb/v0.9/concepts/api/  

and

https://docs.influxdata.com/influxdb/v0.8/api/reading_and_writing_data/

Using examples:

http://10.1.1.2:8086
http://10.1.1.2:8086/db
http://10.1.1.2:8086/db/<dbname>

Return 404s in the output.

**Comment by pstadler** [comment]
What's exactly the problem?

**Comment by mjlyon** [comment]
I am unable to add a connection URL that allows for the connectino to InfluxDB to be made

0.9.5 is the version of InfluxDB I'm using

**Comment by pstadler** [comment]
What is your configuration?

Did you set `INFLUXDB_API_ENDPOINT='<HOST>'`?

**Comment by mjlyon** [comment]
[metrics.sh]
;INTERVAL=2
;DEFAULT_REPORTER=stdout
;DEFAULT_METRICS=cpu,memory,swap,network_io,disk_io,disk_usage
;CUSTOM_REPORTERS_PATH=./reporters/custom
;CUSTOM_METRICS_PATH=./metrics/custom

[metric cpu]
;CPU load percentage.

[metric disk_io]
Disk I/O in MB/s.
DISK_IO_MOUNTPOINT=/dev/md1

;[metric disk_usage]
;Disk usage percentage for a file system at a given mount point.
;DISK_USAGE_MOUNTPOINT=/dev/vda

;[metric heartbeat]
;Send a simple heartbeat in form of an integer '1'.

[metric memory]
;Percentage of used memory.

[metric network_io:network_backplane]
;Network traffic in kB/s.
NETWORK_IO_INTERFACE=backplane

[metric network_io:network_lan]
;Network traffic in kB/s.
NETWORK_IO_INTERFACE=lan

;[metric network_io:network_backplane]
;Network traffic in kB/s.
NETWORK_IO_INTERFACE=backplane

;[metric ping]
;Check if remote host is reachable by sending a single ping.
;Reports '1' if ping was successful, '0' if not.
;PING_REMOTE_HOST=

;[metric swap]
;Percentage of used swap space.

;[reporter file]
;Write to a file or named pipe.
;FILE_LOCATION=

[reporter influxdb]
;Send data to InfluxDB.
;Use http://<ip-of-influxdb-host>:8086/db/<dbname>/series?u=root&p=root'
INFLUXDB_API_ENDPOINT=http://x.x.x.x:8086/db/metrics/series?u=root&p=root
INFLUXDB_SEND_HOSTNAME=true

**Comment by pstadler** [comment]
Please refer to the InfluxDB manual. Their 0.9 docs state that the endpoint looks something like `/write?db=mydb`, while you're using `/db/metrics/series`.
